name: Java CI with Gradle

on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
          with:
            java-version: 11

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          echo "Sleeping for 10"
          sleep 10



