name: Java CI with Gradle

on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          java -jar ${{ github.workspace }}/artifacts/app-order.jar &
          echo "Sleeping for 10"
          sleep 10



