name: Java CI with Gradle

on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
      java -jar ./artifacts/app-mbank.jar &
      echo "Sleeping for 10"
      sleep 10


